### ISSUE TITLE
no crossbow, no infinity, using on inv

### ISSUE THREAD

**Issue by DurianGape** [The-Fireplace/Overlord#188]
Seems whenever i give a skeleton a crossbow, it only attempts to pull back the string but never finishes. Additionally, it seems that infinity doesn't apply when a skeleton uses a bow. Other than that, whenever i open a skeleton's inventory while holding something, it makes me start using that item. Example: I start to drink milk if i right click on the skeleton if the milk bucket is in my hand.

Minecraft 1.17.1
Fabric 0.42.1
Overlord 3.0.1
Fireplace lib 6.0.7

**Comment by The-Fireplace** [comment]
Thank you for providing details. To clarify, does the skeleton have arrows for the crossbow, and does it hold them in its off hand when trying to use the crossbow?
I'll check in to the other two issues in the next update. You don't have to this time, but in the future can you please create multiple issues instead of listing multiple things on one? It makes it easier to track that way. Thanks!

**Comment by DurianGape** [comment]
They do indeed have arrows in their offhand.
Noted! I literally just made an account to bring up these issues so I wasn't sure of the proper etiquette.

**Comment by The-Fireplace** [comment]
All fixed in Overlord 3.0.2
