### ISSUE TITLE
Possible error with this mod and newer builds of Fabric

### ISSUE THREAD

**Issue by Sunconure11** [The-Fireplace/Overlord#223]
https://pastebin.com/cqQ7bitL

**Comment by The-Fireplace** [comment]
What makes you think this is an error with Overlord? There are loads of mods mentioned in that crash report.
Looking at the "Caused By" sections, I'd suspect rats mischief and fabric anvils are why it is failing.

"	Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on useVampireTexture could not find any targets matching 'getTextureLocation(Lladysnake/ratsmischief/common/entity/RatEntity;)Lnet/minecraft/util/Identifier;' in ladysnake.ratsmischief.client.model.RatEntityModel. Using refmap haema-refmap.json [PREINJECT "
"Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method xpLimit(I)I in fabricanvils.mixins.json:AnvilScreenMixin from mod fabricanvils failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabricanvils-refmap.json"
